
package com.hrtp.salesAppService.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IGmmsServiceService", targetNamespace = "http://webservice.gmms.hrt.com/", wsdlLocation = "http://10.51.130.169:10087/AdmApp/service/gmmsService?wsdl")
public class IGmmsServiceService
    extends Service
{

    private final static URL IGMMSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IGMMSSERVICESERVICE_EXCEPTION;
    private final static QName IGMMSSERVICESERVICE_QNAME = new QName("http://webservice.gmms.hrt.com/", "IGmmsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.51.130.169:10087/AdmApp/service/gmmsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IGMMSSERVICESERVICE_WSDL_LOCATION = url;
        IGMMSSERVICESERVICE_EXCEPTION = e;
    }

    public IGmmsServiceService() {
        super(__getWsdlLocation(), IGMMSSERVICESERVICE_QNAME);
    }

    public IGmmsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IGMMSSERVICESERVICE_QNAME, features);
    }

    public IGmmsServiceService(URL wsdlLocation) {
        super(wsdlLocation, IGMMSSERVICESERVICE_QNAME);
    }

    public IGmmsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IGMMSSERVICESERVICE_QNAME, features);
    }

    public IGmmsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IGmmsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGmmsService
     */
    @WebEndpoint(name = "IGmmsServicePort")
    public IGmmsService getIGmmsServicePort() {
        return super.getPort(new QName("http://webservice.gmms.hrt.com/", "IGmmsServicePort"), IGmmsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGmmsService
     */
    @WebEndpoint(name = "IGmmsServicePort")
    public IGmmsService getIGmmsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.gmms.hrt.com/", "IGmmsServicePort"), IGmmsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IGMMSSERVICESERVICE_EXCEPTION!= null) {
            throw IGMMSSERVICESERVICE_EXCEPTION;
        }
        return IGMMSSERVICESERVICE_WSDL_LOCATION;
    }

}
